// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-hK3um5q9qmGMYkW-LB5bRahJZszm1fw',
    appId: '1:545742335119:android:f9a225ede2bf39729a54fa',
    messagingSenderId: '545742335119',
    projectId: 'phoneauthwithoutappcheck',
    storageBucket: 'phoneauthwithoutappcheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqamWpidyebBDsUzCro_UCEkS5tc9qROQ',
    appId: '1:545742335119:ios:ca80790203af37309a54fa',
    messagingSenderId: '545742335119',
    projectId: 'phoneauthwithoutappcheck',
    storageBucket: 'phoneauthwithoutappcheck.appspot.com',
    androidClientId: '545742335119-37rpne8h5m4kfealhdge8fod6n65161c.apps.googleusercontent.com',
    iosClientId: '545742335119-369585ijbp0s2o6dv1tlbsob6u7ihm28.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthWithoutAppCheck',
  );
}
